 - **int** - **28**

In [28]:
from sys import getsizeof

print(f'Size of int: {getsizeof(5000)}')
print(f'Size of int: {getsizeof(50)}')
print(f'Size of float: {getsizeof(50.01)}')
print(f'Size of string: {getsizeof("a")}')
print(f'Size of string: {getsizeof("ab")}')
print(f'Size of string: {getsizeof("abc")}')
print(f'Size of string: {getsizeof("abcdefghe")}')
print(f'Size of list: {getsizeof(["a"])}')
print(f'Size of list: {getsizeof(["a", "b"])}')
print(f'Size of list: {getsizeof(["a", "b", "c"])}')

Size of int: 28
Size of int: 28
Size of float: 24
Size of string: 58
Size of string: 51
Size of string: 52
Size of string: 58
Size of list: 72
Size of list: 80
Size of list: 88

288 <class 'dict'> {'a': 1, 'b': 2, 'c': 3, 'd': [4, 5, 6, 7], ...}
50 <class 'str'> 'e'
66 <class 'str'> 'a string of chars'
50 <class 'str'> 'b'
50 <class 'str'> 'c'
50 <class 'str'> 'a'
50 <class 'str'> 'd'
96 <class 'list'> [4, 5, 6, 7]